// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_screen__screen1 = NULL;
lv_obj_t * ui_image__screen1__background = NULL;
lv_obj_t * ui_image__screen1__shaow = NULL;
lv_obj_t * ui_image__screen1__iconbg = NULL;
lv_obj_t * ui_image__screen1__pinktop = NULL;
lv_obj_t * ui_image__screen1__pinkleft = NULL;
lv_obj_t * ui_image__screen1__bluemid = NULL;
lv_obj_t * ui_image__screen1__blueright = NULL;
lv_obj_t * ui_image__screen1__intersect = NULL;
lv_obj_t * ui_image__screen1__greenleft = NULL;
lv_obj_t * ui_image__screen1__greenleft1 = NULL;
lv_obj_t * ui_image__screen1__bottompink = NULL;
lv_obj_t * ui_image__screen1__hightlight = NULL;
// event funtions

// build funtions

void ui_screen__screen1_screen_init(void)
{
    ui_screen__screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen__screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_image__screen1__shaow = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__shaow, &ui_img_shadow_png);
    lv_obj_set_width(ui_image__screen1__shaow, LV_SIZE_CONTENT);   /// 641
    lv_obj_set_height(ui_image__screen1__shaow, LV_SIZE_CONTENT);    /// 641
    lv_obj_set_x(ui_image__screen1__shaow, -15);
    lv_obj_set_y(ui_image__screen1__shaow, 34);
    lv_obj_set_align(ui_image__screen1__shaow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__shaow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__shaow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__iconbg = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__iconbg, &ui_img_iconbg_png);
    lv_obj_set_width(ui_image__screen1__iconbg, LV_SIZE_CONTENT);   /// 504
    lv_obj_set_height(ui_image__screen1__iconbg, LV_SIZE_CONTENT);    /// 504
    lv_obj_set_x(ui_image__screen1__iconbg, -4);
    lv_obj_set_y(ui_image__screen1__iconbg, 0);
    lv_obj_set_align(ui_image__screen1__iconbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__iconbg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__iconbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__pinktop = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__pinktop, &ui_img_pinktop_png);
    lv_obj_set_width(ui_image__screen1__pinktop, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_image__screen1__pinktop, LV_SIZE_CONTENT);    /// 152
    lv_obj_set_x(ui_image__screen1__pinktop, -43);
    lv_obj_set_y(ui_image__screen1__pinktop, -66);
    lv_obj_set_align(ui_image__screen1__pinktop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__pinktop, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__pinktop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__pinkleft = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__pinkleft, &ui_img_pinkleft_png);
    lv_obj_set_width(ui_image__screen1__pinkleft, LV_SIZE_CONTENT);   /// 294
    lv_obj_set_height(ui_image__screen1__pinkleft, LV_SIZE_CONTENT);    /// 226
    lv_obj_set_x(ui_image__screen1__pinkleft, 47);
    lv_obj_set_y(ui_image__screen1__pinkleft, 34);
    lv_obj_set_align(ui_image__screen1__pinkleft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__pinkleft, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__pinkleft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__bluemid = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__bluemid, &ui_img_bluemiddle_png);
    lv_obj_set_width(ui_image__screen1__bluemid, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_image__screen1__bluemid, LV_SIZE_CONTENT);    /// 263
    lv_obj_set_x(ui_image__screen1__bluemid, 35);
    lv_obj_set_y(ui_image__screen1__bluemid, -26);
    lv_obj_set_align(ui_image__screen1__bluemid, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__bluemid, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__bluemid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__blueright = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__blueright, &ui_img_blueright_png);
    lv_obj_set_width(ui_image__screen1__blueright, LV_SIZE_CONTENT);   /// 269
    lv_obj_set_height(ui_image__screen1__blueright, LV_SIZE_CONTENT);    /// 304
    lv_obj_set_align(ui_image__screen1__blueright, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__blueright, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__blueright, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__intersect = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__intersect, &ui_img_intersect_png);
    lv_obj_set_width(ui_image__screen1__intersect, LV_SIZE_CONTENT);   /// 275
    lv_obj_set_height(ui_image__screen1__intersect, LV_SIZE_CONTENT);    /// 260
    lv_obj_set_x(ui_image__screen1__intersect, -16);
    lv_obj_set_y(ui_image__screen1__intersect, 51);
    lv_obj_set_align(ui_image__screen1__intersect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__intersect, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__intersect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__greenleft = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__greenleft, &ui_img_greenleft1_png);
    lv_obj_set_width(ui_image__screen1__greenleft, LV_SIZE_CONTENT);   /// 287
    lv_obj_set_height(ui_image__screen1__greenleft, LV_SIZE_CONTENT);    /// 217
    lv_obj_set_x(ui_image__screen1__greenleft, 6);
    lv_obj_set_y(ui_image__screen1__greenleft, -25);
    lv_obj_set_align(ui_image__screen1__greenleft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__greenleft, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__greenleft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__greenleft1 = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__greenleft1, &ui_img_greenleft_png);
    lv_obj_set_width(ui_image__screen1__greenleft1, LV_SIZE_CONTENT);   /// 287
    lv_obj_set_height(ui_image__screen1__greenleft1, LV_SIZE_CONTENT);    /// 217
    lv_obj_set_align(ui_image__screen1__greenleft1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__greenleft1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__greenleft1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__bottompink = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__bottompink, &ui_img_bottompink_png);
    lv_obj_set_width(ui_image__screen1__bottompink, LV_SIZE_CONTENT);   /// 74
    lv_obj_set_height(ui_image__screen1__bottompink, LV_SIZE_CONTENT);    /// 144
    lv_obj_set_align(ui_image__screen1__bottompink, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__bottompink, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__bottompink, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image__screen1__hightlight = lv_image_create(ui_screen__screen1);
    lv_image_set_src(ui_image__screen1__hightlight, &ui_img_highlight_png);
    lv_obj_set_width(ui_image__screen1__hightlight, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_image__screen1__hightlight, LV_SIZE_CONTENT);    /// 267
    lv_obj_set_align(ui_image__screen1__hightlight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_image__screen1__hightlight, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image__screen1__hightlight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_screen__screen1_screen_destroy(void)
{
    if(ui_screen__screen1) lv_obj_del(ui_screen__screen1);

    // NULL screen variables
    ui_screen__screen1 = NULL;
    ui_image__screen1__background = NULL;
    ui_image__screen1__shaow = NULL;
    ui_image__screen1__iconbg = NULL;
    ui_image__screen1__pinktop = NULL;
    ui_image__screen1__pinkleft = NULL;
    ui_image__screen1__bluemid = NULL;
    ui_image__screen1__blueright = NULL;
    ui_image__screen1__intersect = NULL;
    ui_image__screen1__greenleft = NULL;
    ui_image__screen1__greenleft1 = NULL;
    ui_image__screen1__bottompink = NULL;
    ui_image__screen1__hightlight = NULL;

}
