// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef UI_SCREEN__SCREEN1_H
#define UI_SCREEN__SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen__screen1
extern void ui_screen__screen1_screen_init(void);
extern void ui_screen__screen1_screen_destroy(void);
extern lv_obj_t * ui_screen__screen1;
extern lv_obj_t * ui_image__screen1__shaow;
extern lv_obj_t * ui_image__screen1__iconbg;
extern lv_obj_t * ui_image__screen1__pinktop;
extern lv_obj_t * ui_image__screen1__pinkleft;
extern lv_obj_t * ui_image__screen1__bluemid;
extern lv_obj_t * ui_image__screen1__blueright;
extern lv_obj_t * ui_image__screen1__intersect;
extern lv_obj_t * ui_image__screen1__greenleft;
extern lv_obj_t * ui_image__screen1__greenleft1;
extern lv_obj_t * ui_image__screen1__bottompink;
extern lv_obj_t * ui_image__screen1__hightlight;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

