// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_screen__screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui_startevents_______initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_highlights_png);    // assets/highlights.png
LV_IMG_DECLARE(ui_img_shadow_png);    // assets/shadow.png
LV_IMG_DECLARE(ui_img_iconbg_png);    // assets/iconbg.png
LV_IMG_DECLARE(ui_img_pinktop_png);    // assets/pinktop.png
LV_IMG_DECLARE(ui_img_pinkleft_png);    // assets/pinkleft.png
LV_IMG_DECLARE(ui_img_bluemiddle_png);    // assets/bluemiddle.png
LV_IMG_DECLARE(ui_img_blueright_png);    // assets/blueright.png
LV_IMG_DECLARE(ui_img_intersect_png);    // assets/Intersect.png
LV_IMG_DECLARE(ui_img_greenleft1_png);    // assets/greenleft1.png
LV_IMG_DECLARE(ui_img_greenleft_png);    // assets/greenleft.png
LV_IMG_DECLARE(ui_img_bottompink_png);    // assets/bottompink.png
LV_IMG_DECLARE(ui_img_highlight_png);    // assets/highlight.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
